language: ruby
rvm:
  - 2.0.0p247
env:
  - RAILS_VERSION='->4.0.2'
  - DB=sqlite
script:
  - bundle update && bundle install
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
  # - bundle exec rake tests
branches:
  only:
    - master
